= INSY Theorie
Peter Klose
1.0.0, 2021-11-28:
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Konzeptionelle Datenmodelle

=== Was ist ein DB-System

4 Komponenten

* Daten
* Hardware
* Software
* Benutzer


=== Unterschied Dateisystem _DS_ / Datenbanksystem _DBS_

[plantuml,Abb2,png]
-----
@startuml
left to right direction

agent A
agent B
agent C
agent D1
agent D2
agent D3

A ---- D1
C ---- D3
B ---- D2



note right of D1
Angestellte Date
end note
note right of D2
Projekt Datei
end note
note right of D3
Angest. - Projekt Datei
end note

@enduml
-----

Sehr schlechte Lösung - viele Nachteile

* Redundanz (Gleiche Daten in mehreren Dateien)
* Bei jedem Programmablauf ist immer der gesamte Datei-Inhalt zu durchsuchen.
* Keine Schutzmaßnahmen
* Allgemeine Routinen müssen in jeder Programmiersprache kodiert werden.
* Änderungen der Dateien haben Auswirkungen auf die Programme.
* Keine Zentrale Kontrolle

=== Datenbank

* DBMS (Software z.B.: ORACLE)
* Datenbasis

//Abb3
[plantuml,Abb2,png]
-----
@startuml
left to right direction

package AnwPgm (batch){}
package AnwPgm (online){}
package Datenbank{
package DMBS{}
package Datenbasis{}
}
AnwPgm (batch) ..> Datenbank
AnwPgm (online) ..> Datenbank


@enduml
-----

=== 3-Schema-Konzept

damit versucht man eine DB in möglichst unabhängige einfach zu wartende Teile zu zerlegen

//Abb5

|===
|AP |Anwendungsprogramm
|ES |Externes-Schema
|IS |Internes-Schema
|KS |Konzeptionelles-Schema
|===

==== Konzeptionelle Schema

logische Gesamtstruktur der Daten, ihrer Eigenschaften und Beziehungen

Bsp Mitarbeiter (MitarbeiterNr, Telefonnummer, SozVers, Beziehung, ...)
====
*SozVers* ... 10-stellig, Nummer, geb. Datum ist eingebettet
*Beziehung* ... Mitarbeiter ist Untergebener von ...
====

==== Internes Schema

Werden alle implementierungsabhängigen Eigenschaften Definiert

z.B.: Speicherart, Zeichensatz, Zugriffspfade, ...

==== Externes Schema

Für die AP _Anwendungsprogramme_ wird nur ein kleiner Ausschnitt zur verfügung gestellt (Nachnahmen und Gehalt) -> nicht aber das Gehalt

== Comming Soon
